Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2020-07, with the labels that each got.

#93 Changes for first Purity 6 support
  collections/ansible_collections/purestorage/flasharray/plugins/module_utils/purefa.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
Labels: bug, enhancement

#94 Add recover snapshot feature
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_snap.py
Labels: enhancement

#96 Add volume_tags module
  collections/ansible_collections/purestorage/flasharray/README.md
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume_tags.py
Labels: documentation, enhancement

#95 Bump release version
  collections/ansible_collections/purestorage/flasharray/galaxy.yml
Labels: documentation

#90 Assume gateway could be empty in pure
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py
Labels: bug

#97 Add ActiveDR pod replica links module
  collections/ansible_collections/purestorage/flasharray/README.md
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod_replica.py
Labels: enhancement

#98 Add support for promotion/demotion of ActiveDR linked pods
  collections/ansible_collections/purestorage/flasharray/galaxy.yml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod.py
Labels: enhancement

#99 Ensure all tag namespaces are exposed, except VASA related
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py
Labels: enhancement

#100 Add SMI-S module
  .github/workflows/main.yml
  collections/ansible_collections/purestorage/flasharray/README.md
  collections/ansible_collections/purestorage/flasharray/galaxy.yml
  collections/ansible_collections/purestorage/flasharray/plugins/doc_fragments/purestorage.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_smis.py
Labels: documentation, enhancement
