Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2021-04, with the labels that each got.

#167 [FIX] Update workflow for black
  .github/workflows/black.yaml
Labels: bug

#170 Add new failure state if restoring to stretched pod
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/170_pgsnap_stretch_pod_fail.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pgsnap.py
Labels: bug

#168 Ensure dsrole doesn't report true for None or null
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/168_dsrole_fix.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_dsrole.py
Labels: bug

#166 Update Remote Assist to support Purity//FA 6
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_ra.py
Labels: bug

#169 New module for SSL Certificates
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/169_add_certs.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_certs.py
Labels: enhancement

#172 Update docs for pycountry
  collections/ansible_collections/purestorage/flasharray/README.md
  collections/ansible_collections/purestorage/flasharray/requirements.txt
Labels: documentation

#177 Ensure API version supports promoted_status field for pods
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/176_fix_promote_api_issue.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
Labels: bug

#174 Allow gateway to be None for network port configuration
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/174_null_gateway.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py
Labels: bug

#175 Check pgname is valid
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/175_check_pgname.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
Labels: bug

#181 Fix idempotent bug when cloning from a source volume.
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
Labels: bug

#179 Do not check for stretched target pod if is source = target
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pgsnap.py
Labels: bug

#182 Allow new volume to be added to existing pgroup
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/182_allow_pgroup_with_create.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
Labels: enhancement

#185 purefa_fs : Fix message and example typos
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_fs.py
Labels: documentation

#186 Add missing README info
  collections/ansible_collections/purestorage/flasharray/README.md
Labels: documentation

#189 Update blackened code
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_endpoint.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pgsched.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pgsnap.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pod_replica.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_policy.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_subnet.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_vg.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_vlan.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume_tags.py
Labels: documentation

#188 Add directory snapshot support
  collections/ansible_collections/purestorage/flasharray/README.md
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/188_add_dirsnap.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_dirsnap.py
Labels: enhancement

#187 Add AD support
  collections/ansible_collections/purestorage/flasharray/README.md
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/187_add_ad.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_ad.py
Labels: enhancement

#195 Remove debug code and redundant docs
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume_tags.py
Labels: bug, documentation
