Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2022-05, with the labels that each got.

#278 Add info for PG snapshots and support for PG safemode
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/278_pgsnap_info.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py
Labels: enhancement

#279 PG SafeMode support
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/279_pg_safemode.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
Labels: enhancement

#280 Allow multihost creation with no suffix
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/280_multihost_no_suffix.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_host.py
Labels: bug

#277 Add FileSystem Replication support
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/277_add_fs_repl.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_fs.py
Labels: enhancement

#285 Release 1.13.0
  collections/ansible_collections/purestorage/flasharray/CHANGELOG.rst
  collections/ansible_collections/purestorage/flasharray/changelogs/.plugin-cache.yaml
  collections/ansible_collections/purestorage/flasharray/changelogs/changelog.yaml
  collections/ansible_collections/purestorage/flasharray/galaxy.yml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_fs.py
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
Labels: Release

#290 fix: no changed when new_volumes is empty
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_hg.py
Labels: bug

#288 Allow zero as valid pgroup schedule parameters
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/288_zero_params.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pgsched.py
Labels: bug

#292 Fix bind password idempotency
  collections/ansible_collections/purestorage/flasharray/changelogs/fragments/292_fix_ds_password.yaml
  collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_ds.py
Labels: bug, enhancement
