Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2023-12, with the labels that each got.

#512 Fix clearing DS certificate
  plugins/modules/purefa_ds.py
Labels: bug

#516 Update create_pgsnapshot in purefa_pgsnap.py renaming throttle parame…
  changelogs/fragments/516_fix_throttle.yaml
  plugins/modules/purefa_pgsnap.py
Labels: bug

#519 Add CBS expansion module
  README.md
  changelogs/fragments/519_add_cloud_capacity.yaml
  plugins/module_utils/version.py
  plugins/modules/purefa_cbsexpand.py
  plugins/modules/purefa_info.py
Labels: enhancement

#518 Add support for NFS policy security flavors
  changelogs/fragments/518_nfs_security.yaml
  plugins/modules/purefa_info.py
  plugins/modules/purefa_policy.py
Labels: enhancement

#520 Change user_agent string contents
  README.md
  changelogs/fragments/520_add_distro.yaml
  plugins/module_utils/purefa.py
  plugins/modules/purefa_connect.py
  plugins/modules/purefa_token.py
Labels: enhancement

#441 Change version checking to REST 2 methodology
  changelogs/fragments/441_v2_version.yaml
  plugins/doc_fragments/purestorage.py
  plugins/modules/purefa_ad.py
  plugins/modules/purefa_admin.py
  plugins/modules/purefa_apiclient.py
  plugins/modules/purefa_certs.py
  plugins/modules/purefa_default_protection.py
  plugins/modules/purefa_directory.py
  plugins/modules/purefa_dirsnap.py
  plugins/modules/purefa_eradication.py
  plugins/modules/purefa_export.py
  plugins/modules/purefa_file.py
  plugins/modules/purefa_fs.py
  plugins/modules/purefa_info.py
  plugins/modules/purefa_kmip.py
  plugins/modules/purefa_logging.py
  plugins/modules/purefa_messages.py
  plugins/modules/purefa_offload.py
  plugins/modules/purefa_policy.py
  plugins/modules/purefa_saml.py
  plugins/modules/purefa_smis.py
  plugins/modules/purefa_snmp_agent.py
  plugins/modules/purefa_sso.py
  plugins/modules/purefa_syslog_settings.py
  requirements.txt
Labels: enhancement

#521 Release 1.25.0
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  galaxy.yml
Labels: Release
