Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2023-11, with the labels that each got.

#497 fixes issues with adding new parts to a subject when creating a CSR
  changelogs/fragments/496_fix_cert_signing.yaml
  plugins/modules/purefa_certs.py
Labels: bug

#498 Allow new PG to be created with both target and objects specified
  changelogs/fragments/498_fix_pg_creation.yaml
  plugins/modules/purefa_pg.py
Labels: bug

#495 Quick fix for deleted pgroups
  changelogs/fragments/495_add_del_pgroup_info.yaml
  plugins/modules/purefa_info.py
Labels: bug

#499 REST 2.27 Support: nsid and deprecate Snap2NFS
  changelogs/fragments/499_rest_227.yaml
  plugins/modules/purefa_info.py
  plugins/modules/purefa_offload.py
Labels: enhancement

#501 Fix incorrect use of breaking_changes flag in changelogs
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/482_schedule.yaml
  changelogs/fragments/483_missing_replicate.yaml
Labels: documentation

#502 Release 1.23.0
  CHANGELOG.rst
  changelogs/.plugin-cache.yaml
  changelogs/changelog.yaml
  galaxy.yml
Labels: Release

#506 Fix issue with disabling schedules
  changelogs/fragments/506_disable_pgsched.yaml
  plugins/modules/purefa_pgsched.py
Labels: bug

#505 Fix DNS deletion attribute error
  changelogs/fragments/505_dns_attribute.yaml
  plugins/modules/purefa_dns.py
Labels: bug

#508 Fix deleting management DNS entries
  plugins/modules/purefa_dns.py
Labels: bug

#509 Add DNS check_peer and cert upload to DNS
  changelogs/fragments/509_check_peer.yaml
  plugins/modules/purefa_ds.py
Labels: enhancement

#511 Add hardware LED control module
  README.md
  plugins/modules/purefa_hardware.py
Labels: enhancement

#513 Add suffix support for offload snapshots
  changelogs/fragments/513_remote_snapshot_suffix.yaml
  plugins/modules/purefa_snap.py
Labels: documentation, enhancement
