Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2024-09, with the labels that each got.

#628 Fix AttributeErrors causing early, unflagged, failure
  changelogs/fragments/628_inventory_fix.yaml
  plugins/modules/purefa_inventory.py
Labels: bug

#631 Fix unreferenced variable
  changelogs/fragments/631_fix_alert.yaml
  plugins/modules/purefa_alert.py
Labels: bug

#627 Ensure NVMe hosts cannot be multi-protocol
  plugins/modules/purefa_host.py
Labels: bug, documentation

#634 Fix documentation
  plugins/modules/purefa_pod_replica.py
Labels: documentation

#635 Update directory info
  changelogs/fragments/635_filesystem_update.yaml
  plugins/modules/purefa_info.py
Labels: bug

#632 Fix eradciation timer issue
  changelogs/fragments/632_eradication_timer.yaml
  plugins/modules/purefa_eradication.py
Labels: bug

#638 Fix issue with pod deletion
  changelogs/fragments/638_delete_pod.yaml
  plugins/modules/purefa_pod.py
Labels: bug

#639 Update hg to REST2
  plugins/modules/purefa_hg.py
Labels: REST v2

#633 Fix netaddr compatability issue
  README.md
  changelogs/fragments/633_netaddr_fix.yaml
  plugins/modules/purefa_network.py
  requirements.txt
Labels: bug, documentation

#642 Errors out when pgroup and add_to_pgs used incorrectly
  changelogs/fragments/642_volume_pg_fix.yaml
  plugins/modules/purefa_volume.py
Labels: bug

#643 Ensure response with bad power supply
  plugins/modules/purefa_inventory.py
Labels: bug

#641 Fix keep_for parameter
  changelogs/fragments/641_dirsnap_keep_for.yaml
  plugins/modules/purefa_dirsnap.py
  plugins/modules/purefa_info.py
Labels: bug, enhancement
