Repository Pure-Storage-Ansible/FlashArray-Collection, pull requests merged in 2024-12, with the labels that each got.

#676 Fixes moving protected volume bug for volume group
  changelogs/fragments/676_volume_vg_fix.yaml
  plugins/modules/purefa_volume.py
Labels: bug

#683 docs: fix typo in `plugins/doc_fragments/purestorage.py`
  plugins/doc_fragments/purestorage.py
Labels: documentation

#678 Add realms info
  changelogs/fragments/668_realms_info.yaml
  plugins/modules/purefa_info.py
Labels: enhancement

#677 Add network performance data
  changelogs/fragments/677_networ_perf.yaml
  plugins/modules/purefa_info.py
Labels: enhancement
